### ISSUE TITLE
Sync up between DynamoDB and ES 

### ISSUE THREAD

**Issue by PrimKruskal** [awslabs/fhir-works-on-aws-persistence-ddb#56]
We had few ES clusters corruption happened and data is not in sync between dynamoDB and ES data-stores.  Is there any enhancements planned for syncing up data between these data stores ? 

ES is always prone to data unreliability and having a function within persistence ddb will help in these type of situations.

**Comment by rsmayda** [comment]
Hey great question! As you have found we don't have explicit sync script from DynamoDB to ElasticSearch. This is not on our roadmap but we would be happy to take a contribution from the community. What I think would be good acceptance criteria would be:
1. re-sync all data
2. re-sync a specific ES index
3. delete all ES indexes and re-build them
4. delete a specific index and re-build them

In the mean time here is an article and script I've found online that I believe would work:
- script: https://github.com/vladhoncharenko/aws-dynamodb-to-elasticsearch/blob/master/scripts/post_to_es_from_dynamodb.py
- article: https://medium.com/@vladyslavhoncharenko/how-to-index-new-and-existing-amazon-dynamodb-content-with-amazon-elasticsearch-service-30c1bbc91365

**Comment by rsmayda** [comment]
In [3.0.0 FHIR Works deployment](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/CHANGELOG.md#300-2021-06-15) we released a change that makes our search & persistence layer use ES aliases instead of calling ES indices directly. In addition in [2.7.0](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/CHANGELOG.md#270-2021-04-30) we released a change that captures all ddbToES failures in a DLQ.
